### ISSUE TITLE
freeze about 10 sec on search in opened file

### ISSUE THREAD

**Issue by dmitrychepel** [EugeneManushkin/CtagsSourceNavigator#25] opened 2018-05-23 08:50 UTC
freeze about 10 sec on search in opened file
steps to repro
1. generate tags by universal ctags
2. goto to some file (could provide by request and index too)
3. open menu "search in opened file"
4. plugin freezes

**Comment by EugeneManushkin** [comment] 2018-07-09 12:10
Reproduced on file containing ~ 40 000 tags. 
Probable solution: search tags by name then filter found tags by file

**Comment by EugeneManushkin** [comment] 2022-05-31 16:25
This happened due to almost lineral complexity of searching algorithm.
Fixed in #85.

**Closed by EugeneManushkin** 2022-05-31 16:25 UTC
Labels: bug
